import { Container } from '@mui/material';
import './global.css';
import { TrpcProvider } from '@warpportal/trpc/client';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TrpcProvider>
      <html lang="en">
        <body>
          <Container>{children}</Container>
        </body>
      </html>
    </TrpcProvider>
  );
}
